// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8FA7G0Y_3-Yg-K4ONIx5DKFwRqrNmcTU',
    appId: '1:892229917743:web:fdc0d0aa2a34244930fada',
    messagingSenderId: '892229917743',
    projectId: 'shopease-98e5b',
    authDomain: 'shopease-98e5b.firebaseapp.com',
    storageBucket: 'shopease-98e5b.firebasestorage.app',
    measurementId: 'G-4LJDJM4NWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFgCLxjw0ItyYTkGHYl_8Uvdv70TXDjoo',
    appId: '1:892229917743:android:111805febd402b3f30fada',
    messagingSenderId: '892229917743',
    projectId: 'shopease-98e5b',
    storageBucket: 'shopease-98e5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7Ne1JF0Yg6yvjKeqK2x6qfELlk-IbafI',
    appId: '1:892229917743:ios:2899ca74faccae3b30fada',
    messagingSenderId: '892229917743',
    projectId: 'shopease-98e5b',
    storageBucket: 'shopease-98e5b.firebasestorage.app',
    iosBundleId: 'com.example.shopease',
  );
}
